# Generated by Django 4.2.5 on 2023-11-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="multivitamins",
            name="id",
        ),
        migrations.AlterField(
            model_name="multivitamins",
            name="name",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
