# Generated by Django 4.2.5 on 2023-11-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_remove_multivitamins_id_alter_multivitamins_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
