# Generated by Django 4.2.5 on 2023-12-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="multivitamins",
            name="id",
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
